### PR TITLE
First iteration of the a graph representation

### PR DESCRIPTION
**Pull request by danieldk**
cc: @sebpuetz, @divefish

This is not a pull request to be merged, but to refine the first iteration of the graph representation. This largely follows what we discussed in #4. There are still two open questions when it comes to the basic dependency graph data structure:

1. How to represent the distinct dependency relations and projective dependency label columns?

One way to approach this would be to make an enum for dependency relations with variants `NonProjective` and `Projective`. This would allow us to add the relations from both columns to the same graph. The downside is that it would clutter the graph more and makes graph operations a bit harder. E.g. now we can always assume that there is just one incoming edge when a token has a head. In this approach, a token could have a `NonProjective` relation to its head, a `Projective` relation, neither, or both.

The projective columns are not used much in practice. Most people store projective trees in the non-projective column as well. CoNLL-U does not even use the PHEAD and PDEPREL columns anymore. Though I have seen some treebanks that store secondary edges in the projective columns.

2. How to handle dependency edges without labels?

A treebank can only annotate the head of a token and leave the head relation column blank. Of course, it would be easy to represent optional labels, we could change the label type to `Option<String>`. Of course, this requires a lot of unnecessary unwrapping when a treebank always has relation labels. An alternative could be to make the relation type a parameter of `DepGraph` and we could, when reading a file, provide the option to read into `DepGraph<String>` or `DepGraph<Option<String>>` where the former would fail if a relation label is absent. Downside: introducing a type parameter.

### CODE REVIEW

**Comment by sebpuetz** [comment]
> 1. How to represent the distinct dependency relations and projective dependency label columns?

I think there is another more fundamental question here, should both kinds of graphs be represented through the same type? Projectivizing a graph could result in a `ProjectivizedGraph` if access to non-projective graphs and projective graphs can be mutually exclusive. Although I wouldn't know how to represent graphs built from a treebank annotated with both kinds of dependencies in this case.
If both should be represented in the same graph it would make utilizing the methods of petgraph much harder. e.g. before doing a traversal on the projective edges it would be necessary to remove all non-projective edges. Otherwise all those methods would have to be re-implemented with matching on the edge-type.

> 2. How to handle dependency edges without labels?

I don't think adding a type parameter would be a problem here

**Comment by danieldk** [comment]
> I think there is another more fundamental question here, should both kinds of graphs be represented through the same type? Projectivizing a graph could result in a `ProjectivizedGraph`

For clarity: it is not so much about projectivizing the graph, it is that the CoNLL-X format has two head and dependency relation columns. So a sentence in CoNLL-X can be associated with two graphs. The CoNLL-X specification only requires that the second graph is always projective. So in order to represent the CoNLL-X data completely in memory, you need to represent both the regular graph (head/headrel) and the graph that is always projective (phead/pheadrel). If you don't represent both graphs together, serializing the graph to CoNLL-X would result in a loss of information if the original data had two graphs.

> If both should be represented in the same graph it would make utilizing the methods of petgraph much harder. e.g. before doing a traversal on the projective edges it would be necessary to remove all non-projective edges.

Yes, one would have to call `filter` on all iterating methods.

> > 1. How to handle dependency edges without labels?
> 
> I don't think adding a type parameter would be a problem here

Maybe not ;). Of course, we could always set a default type for the type parameter.

To keep things simple, I am assuming that the opposite is invalid: having a head relation without a head ;).

**Comment by danieldk** [comment]
I did a partial implementation of two types of relations in one graph in the [p-np-partial](https://github.com/danieldk/conllx-rs/tree/p-np-partial) branch. Can't say I am happy.

**Comment by sebpuetz** [comment]
>For clarity: it is not so much about projectivizing the graph, it is that the CoNLL-X format has two head and dependency relation columns. So a sentence in CoNLL-X can be associated with two graphs. The CoNLL-X specification only requires that the second graph is always projective. So in order to represent the CoNLL-X data completely in memory, you need to represent both the regular graph (head/headrel) and the graph that is always projective (phead/pheadrel). If you don't represent both graphs together, serializing the graph to CoNLL-X would result in a loss of information if the original data had two graphs.

I'm aware of this. There would be a workaround by giving the `graph::Token` fields holding an `Option<String>` and `Option<usize>` representing the graph that's currently not reflected in the `petgraph`. Conversion would not be expensive since only the edges would need to be updated. Serialization is still possible since all information is available. This would allow cheap iteration and no need to filter/match anything.

**Comment by danieldk** [comment]
But a bit hacky... Another approach I have been considering is to just have two separate graphs wrapped in `DepGraph`. Downside: every token is stored twice; or one graph has references to tokens; or the graphs use `Rc<RefCell<Token>>`.

**Comment by sebpuetz** [comment]
I was going to place this into an edit, but anyways another argument against having both kinds of edges present:

To my understanding a `DepGraph` containing both projective and non-projective edges at the same time could not utilize some `petgraph` methods like `is_cyclic_directed()` or even `DFS` or `BFS`. So basically many of the advantages of having the `petgraph` in the first place are lost.

Is it ever the case that a user wants to traverse a graph on projective and non-projective edges at the same time? If not I think there really aren't too many downsides of storing the other "edge version" in `Option`s.

**Comment by danieldk** [comment]
> To my understanding a `DepGraph` containing both projective and non-projective edges at the same time could not utilize some `petgraph` methods like `is_cyclic_directed()` or even `DFS` or `BFS`. So basically many of the advantages of having the `petgraph` in the first place are lost.

Indeed. Good point.

> Is it ever the case that a user wants to traverse a graph on projective and non-projective edges at the same time?

When people overload the other dependency fields for secondary edges. Some treebanks have secondary edges, and this the most straightforward way to model it. The other is using the features field.

We have also used the extra field sometimes to annotate gold-standard with parser errors in the same treebank. This works nice with some treebank tools such as TüNDRA, which then displays the errors as secondary edges.

I realize that both scenarios are overloading the meaning of the projective dependency fields, but people tend to do such things ;).

**Comment by danieldk** [comment]
> Another approach I have been considering is to just have two separate graphs wrapped in `DepGraph`. Downside: every token is stored twice; or one graph has references to tokens; or the graphs use `Rc<RefCell<Token>>`.

I think this could work by putting the `Token` instances in a `Vec`. Then the graphs could be `DiGraph<(), String>`. So, we don't pay for storing tokens twice and we can store both structures. It may not be as nice for people who use `into_inner` and remove/insert tokens, but for applications that just need the `DepGraph` abstraction it is nice.

**Comment by sebpuetz** [comment]
> I realize that both scenarios are overloading the meaning of the projective dependency fields, but people tend to do such things ;).

I'd suggest when people do this make them bite the bullet and construct a new graph from the secondary edges given in the original graph. If parallel access is necessary, two seperate graph structures are necessary anyways.

**Comment by danieldk** [comment]
> If parallel access is necessary, two seperate graph structures are necessary anyways.

But then you cannot easily serialize them back to CoNLL-X, you'd have to write everything into `Option`s again. And the writer functions need be made aware of which graph is which.

**Comment by sebpuetz** [comment]
> But then you cannot easily serialize them back to CoNLL-X, you'd have to write everything into Options again. And the writer functions need be made aware of which graph is which.

That's a good point, having a `PrimaryGraph` and `SecondaryGraph` seems a bit...odd. Placing some marker in the `DepGraph` is rather hacky, too.

**Pull request closed without merging**
