### PR TITLE
Second iteration of the a graph representation

### PR DESCRIPTION
**Pull request by danieldk**
cc: @sebpuetz, @DiveFish

Again not a pull request to be merged, but to refine the second iteration of the graph representation.

In this iteration, I introduced a `Sentence` type, which can be indexed to retrieve tokens. It also offers `graph`/`graph_mut`/`proj_graph`/`proj_graph_mut` to get the graph/non-projective graph as a immutable/mutable reference. rustdoc at:

https://scratch.danieldk.eu/graph-repr-iter2/conllx/graph/struct.Sentence.html

The API is by no means complete, but it's to experiment with this approach. I am pretty happy so far.

### CODE REVIEW

**Comment by sebpuetz** [comment]
Allocating the edge `String`s twice is not very nice but I don't see a work around. A `Vec<String>` and `usize`s as edge weights wouldn't work without iterating over all edges on every update to the edges.

I have some trouble to imagine a nice way to give mutable access to the inner `Graph`s here. While it's nice and clean to update the edges and push tokens to the end, there's no way to filter a graph, insert or remove `Node`s.
I understand that giving mutable access to a single graph is not feasible since it will invalidate the `Sentence` struct as there is no guarantee that the indices (or even the two graphs representing the same sentence) stay in sync.

**Comment by danieldk** [comment]
> Allocating the edge `String`s twice is not very nice but I don't see a work around. A `Vec<String>` and `usize`s as edge weights wouldn't work without iterating over all edges on every update to the edges.

Which edge `String`s are allocated twice?

> I have some trouble to imagine a nice way to give mutable access to the inner `Graph`s here. While it's nice and clean to update the edges and push tokens to the end, there's no way to filter a graph, insert or remove `Node`s.
> I understand that giving mutable access to a single graph is not feasible since it will invalidate the `Sentence` struct as there is no guarantee that the indices (or even the two graphs representing the same sentence) stay in sync.

Indeed. In this approach, if you remove/insert a token, you have to update both the graphs with it (in a tedious manner). I guess one way around this would be to add an indirection. But that makes working with the raw graph even more cumbersome.

Meh, they should've never added these extra projective columns to CoNLL-X ;).

**Comment by sebpuetz** [comment]
> Which edge Strings are allocated twice?

My point was actually incorrect. I assumed that both graphs are always initialized and populated. Which probably is not the case, as it would be misleading if the projective graph would be a copy of the non-projective graph in absence of an actually projective graph.
So there's actually no difference from the `Vec<Token>` representation wrt. allocating dependency labels ;)

**Comment by sebpuetz** [comment]
Although you didn't like my idea of storing secondary edges+labels internally I implemented it in my [fork](https://github.com/sebpuetz/conllx-rs/blob/8627ecb0c08c4c21a73de928aa7fca98d6f26c36/src/graph.rs#L208-L242) to see how this would work out. 
~~If there is a way to differentiate between the DepGraph and the PDepGraph through the type system while not having to implement all methods twice, that would be a nice improvement.~~
If a user wants to treat a `DepGraph<Projective>` and a `DepGraph<NonProjective>` in the same manner they would have to take the detour through `into_inner()` and reconstruction through the `from_graph()` methods.

This iteration doesn't offer any methods on the PDepGraph yet and the dependency labels are mandatory, but that can easily be changed. 

_edit:_ I pushed a slightly changed version to the same branch in my fork. Instead of using different structs I used `PhantomData` to differentiate between `Projective` and `NonProjective` graphs.

**Pull request closed without merging**
