### PR TITLE
Third iteration of the a graph representation

### PR DESCRIPTION
**Pull request by danieldk**
cc: @sebpuetz, @DiveFish

Again not a pull request to be merged.

In this iteration, I took the graph view approach of iteration 2, but overhauled the internal representation. There is again a `Sentence` type, but rather than storing two graphs it again stores one graph `DiGraph<Node, Edge>`. However `Edge` is now a tuple `(Projectivity, Option<String>)` where `Projectivity` is an enum of `Projective` and `NonProjective`.

As we know, this approach make some operations a bit more tedious - you cannot just get the first incoming edge of a dependent, but that for normal use this is now nicely wrapped in the `Graph` and `GraphMut` views. From the daily user's perspective, who uses the view, the projective and non-projective graphs are disjoint.

One benefit of this representation over using two disjoint graphs is that it makes it easier to add/remove tokens to the inner graph. It would need the mapping `Vec<NodeIndex>` to determine the order when converting back to `Sentence`, but insertions/removals do not require rewriting the graph since the node <-> token indirection is gone.

https://scratch.danieldk.eu/graph-repr-iter3/conllx/graph/struct.Sentence.html

### CODE REVIEW

**Comment by sebpuetz** [comment]
~~In my opinion this is the best of the three. Although the problem remains that using `petgraph`s methods is impossible because of the encapsulation (which obviously is necessary with this approach).~~

_edit:_ My comment is wrong, I didn't catch the `From` implementation.

**Comment by sebpuetz** [comment]
My previous comment was incorrect but I think there's something that might make life a little easier.
At this point it's only possible to get a `DiGraph` by destructuring the `Sentence`. It might be nice to have a method returning a clone of the inner graph or maybe a immutable reference. 
I'm unsure how common the use case would be but this would allow a user to clone the inner `DiGraph`, filter the edges for the desired `Projectivity` and use whatever `petgraph` method they want without mutating the original `Sentence`.
That's also possible at this time but it requires reconstruction of the `Sentence` from a `DiGraph` which is most likely going to include some checks like verification of the singleheadedness or acyclicity.

**Comment by danieldk** [comment]
I think this is a good idea! I think returning a reference to the `DiGraph` works the best. Since `Graph` implements `Clone`, one could always clone the `DigGraph` reference to get a copy.

**Comment by danieldk** [comment]
Something like this? f2222ce12a0519a6ae0f185016d3cbefb8f9bf48

I guess for both `From` instances we should also provide some non-train methods, since `From`/`Into` can be awkward at times. Maybe `into_inner()`/`inner_ref()`? Or perhaps `into_inner()`/`get_ref()`to stick more to `std` naming?

**Comment by sebpuetz** [comment]
I would go with `into_inner() / get_ref()` or straying from the `std` conventions and use something more verbose like `graph_ref()` as it's not all that intuitive what `inner` refers to in a `Sentence` struct.

**Comment by danieldk** [comment]
Added in 0035e3a17f00e8bf707b0080cd6f03b4c8ba78c0.

`Reader` and `Writer` now also work with this representation. Large remaining todo: projectiviation/deprojectivization.

**Comment by danieldk** [comment]
Everything within the crate has been converted, including projectivization/deprojectivization: c7c443fd3528ec1128ccfa3457acb95ef1627b07

I will do some cleaning and then try to convert conllx-utils to see what APIs we might be missing.

**Comment by danieldk** [comment]
I finally had time to look at this again, and now all of conllx-utils is converted. I added some more convenience methods and then it was all straightforward. Even `conllx-cycle` was easy, I used the `EdgeFiltered` adapter, which creates a view of the graph without the projective (or non-projective) edges. The branch:

https://github.com/danieldk/conllx-utils/tree/graph-repr-wip

I am pretty happy with how things are now and will probably soon do a PR. One last thing I'd like to do is some benchmarks, especially with utilities that do not use the graph representation.

**Comment by danieldk** [comment]
I did some benchmarks on some of the conllx-utils with TüBa-D/Z (95,595 sentences). Results are best of 3 runs. **Old** is with the master version of `conllx`, **New** with the graph representation.

**Utility**  | **Old** | **New**
------------ | ------- | -------
cleanup      | 3.078   | 3.532
cycle        | 1.676   | 1.623
expandmorph  | 3.615   | 4.075
merge        | 4.553   | 5.423
projectivize | 4.712   | 4.609
text         | 1.649   | 1.726
triples      | 1.813   | 1.912

As expected, the utilities that do not use dependency relations at all (cleanup, expandmorph, merge, text) are slower. Those that do use relations are fairly close together. I seems to be a relatively small regression in performance (at most ~16%) for a much nicer representation.

**Pull request closed without merging**
